### ISSUE TITLE
Instead of looping around, use dashboard/web to trigger restart

### ISSUE THREAD

**Issue by galderz** [infinispan-demos/streaming-data-workshop#16]
I've been playing with the looping around the injectors and it can shoot up CPU usage if not stopped.

A better idea might be to do to the following: when either the delay dashboard or the train position is map is loaded, we kick off both injectors. When these finish, we can notify the web or dashboard and ask the user to reload the page or restart the dashboard. Upon reload/restart, we start the injection again.

If the user reloads/restarts and the injector has not finished, we ignore the request and carry on with the current injection.

**Comment by tsegismont** [comment]
Closed via 4a841f32e6f1ed3ecf803f24650857ffa317eabb
