### ISSUE TITLE
Push UI model

### ISSUE THREAD

**Issue by galderz** [infinispan-demos/streaming-data-workshop#4]
Use push techniques for pushing train position changes. The UI currently checks a RESTful endpoint where it regularly gets a snapshot of the train positions. This is not very optimal. A push model where the backend pushes when there are position changes would be more suitable.

Thomas started a branch with this approach but it’s not fully working (see [here](https://github.com/infinispan-demos/streaming-data-workshop/tree/push_model_ui))

**Comment by tsegismont** [comment]
For the record, the event bus bridge is working, but when the Redux store
is updated, nothing happens.

2017-09-19 11:03 GMT+02:00 Galder Zamarreño <notifications@github.com>:

**Comment by tsegismont** [comment]
Closed via #33
