### ISSUE TITLE
Injector verticle should wait for data to be loaded before terminating

### ISSUE THREAD

**Issue by galderz** [infinispan-demos/streaming-data-workshop#6]
Currently the injector finishes the moment the file has been exhausted. Instead, the injector should wait until the last item has been stored in the data grid.

**Comment by tsegismont** [comment]
What's the difference between file exhausted and last item stored in the grid? And what do you mean with "finishes"?

**Comment by tsegismont** [comment]
@galderz I can confirm there are duplicate `stopId.` The uniqueness ratio is around 1 out of 3.

**Comment by galderz** [comment]
Ok, not an issue then. We'll tighten things up later on.
